# Generated by Django 5.1.2 on 2025-03-23 11:40

import config.utils.image_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[config.utils.image_validators.validate_image_resolution, config.utils.image_validators.validate_image_size]),
        ),
    ]
